parameters:
    oro_help.twig.help_link_provider.class: Oro\Bundle\HelpBundle\Twig\HelpLinkProvider
    oro_help.twig.extension.class: Oro\Bundle\HelpBundle\Twig\HelpExtension

services:
    oro_help.twig.help_link_provider:
        class: %oro_help.twig.help_link_provider.class%
        scope: request
        arguments:
            - @controller_name_converter
            - @request

    oro_help.twig.extension:
        class: %oro_help.twig.extension.class%
        arguments:
            - @oro_help.twig.help_link_provider
        tags:
            - { name: twig.extension }
